### PR TITLE
Add WordPress profile area

### PR DESCRIPTION
**Pull request by marksabbath**
**Summary of change:**
This PR brings the WordPress profile into AB `block-author-profile`.

**This PR has been:**
- [x] Linted for syntax errors
- [x] Tested against the WordPress coding standards
- [x] Tested with the bundled test suite(s)

**How to test:**
- Download the branch;
- Add a new `block-author-profile`;
- Add any value to `WordPress URL`;
- The WordPress icon as a link should show.

**Closes** #201

**Suggested Changelog Entry:**
* Add WordPress Profile URL section on `block-author-profile`

### CODE REVIEW

**Comment by marksabbath** [comment]
> This looks good to me and works fine. The only potentially "weird" thing to me is the label. "WordPress URL"... mainly because WordPress is software. But that's just a minor quibble. We're referring to wordpress.org profile here, right @marksabbath? Any thoughts @mikemcalister?

Yeap, exactly @mindctrl we could add a description as we have in the email field making in clear. Something like:

_"Use here your [wordpress.org](https://wordpress.org) profile."_

**Comment by mikemcalister** [comment]
What about "WordPress Profile URL"? Great addition here, @marksabbath!

**Comment by marksabbath** [comment]
> What about "WordPress Profile URL"? Great addition here, @marksabbath!

Definitely works for me. I'll make the change and push here :)

**Comment by mindctrl** [comment]
Sounds good, thanks @marksabbath!

**Comment by mindctrl** [comment]
Merged here: https://github.com/studiopress/atomic-blocks/commit/916f875e7a7f64a2d45921811a80c3a1e9723dc3

Thanks @marksabbath!

**Pull request closed without merging**
