### PR TITLE
Update readme to inform users of Genesis Blocks

### PR DESCRIPTION
**Pull request by mindctrl**
Adds notice to readme.txt informing users of the move to Genesis Blocks. This text came from the existing admin page text, per Bryan's recommendation.

Closes [BH-548](https://wpengine.atlassian.net/browse/BH-548).

### CODE REVIEW

**Review by nickcernis — APPROVED** [review]
The readme change looks good! Happy to re-review when CI passes if needs me (looks like the build was cancelled manually?).

**Comment by mindctrl** [comment]
> looks like the build was cancelled manually?

Yes I cancelled those. The original commit for the txt file update resulted in a failed Circle job [here](https://app.circleci.com/pipelines/github/studiopress/atomic-blocks/749/workflows/7016e25e-d168-4c9c-a1a5-dc209825a189/jobs/3950).

Not sure what changed exactly. I started following the suggestions in the messages, to see where that leads, which was [more failed jobs](https://app.circleci.com/pipelines/github/studiopress/atomic-blocks?branch=BH-548). I cancelled the last one due to the PHP 5.6 problem. Will dig into that shortly.

**Comment by nickcernis** [comment]
@mindctrl Looks like our Circle CI config is using [Composer 2](https://laravel-news.com/composer-2), affecting package compatibility.

We're seeing similar failures in Genesis: 
https://app.circleci.com/pipelines/github/studiopress/genesis/992/workflows/99a0b787-4775-4938-b10b-9836113e9261/jobs/4825

If this turns into a rabbit hole due to PHP 5.6 support we could try using composer 1? We're installing it manually in the `prepare_environment` step at the moment and its now defaulting to 2.0.2: https://app.circleci.com/pipelines/github/studiopress/atomic-blocks/751/workflows/65f74174-1242-4430-96e4-bbf2a0455f6d/jobs/3961

It looks like you can pass a `--version` flag to composer-setup.php: https://getcomposer.org/download/

**Comment by mindctrl** [comment]
@nickcernis thanks for the info! I didn't notice the failure also happening in the Genesis repo.

After following the suggestions in the failures and still seeing some issues, I've walked back those changes in favor of installing Composer 1.x for now. We can follow that rabbit hole another day.

**Review by nickcernis — APPROVED** [review]
Smoke tested new zip from Circle and confirmed all seems well.

**Pull request merged**
