### PR TITLE
Add category to Post Grid block

### PR DESCRIPTION
**Pull request by markkelnar**
**Summary of change:**
Adds an option to display post categories. #155.

### CODE REVIEW

**Comment by mikemcalister** [comment]
Looking better, thanks! I notice a rogue `:` being output before categories show up. A few more thoughts for everyone: 

- Should we also add an option to limit how many categories are output. If someone has 6 categories, we probably don't want to output all of those. 
- Should we allow them to customize the `Categories` tag? Maybe they want to put something like `Posted in:` or whatever. 
- Would the category output be better off under the author/date?

**Comment by mindctrl** [comment]
> Should we also add an option to limit how many categories are output. If someone has 6 categories, we probably don't want to output all of those.

Good question. I can see the benefit of not showing a bunch of categories. I think it would be ok to ship without this option to see what kind of feedback we get.

> Should we allow them to customize the Categories tag? Maybe they want to put something like Posted in: or whatever.

Definitely think we need this based on experience in support. People like changing this wording up, or simply removing the words in favor of just the category links.

> Would the category output be better off under the author/date?

I can see that. It would be cool if we could let people place it where they want.

**Comment by markkelnar** [comment]
I had some of these same thoughts would testing it.  How would that work to make it so configurable?  Would it work better as its own block?

**Comment by markkelnar** [comment]
This PR is so old and probably needs some work.  Can reopen if still needed.

**Pull request closed without merging**
