### PR TITLE
Updates for basic AMP compatibility

### LINKED ISSUE #111: AMP compatibility
We want to make Atomic Blocks compatible with AMP as much as is possible and reasonable. This issue will track all the changes required for that. I'll update the list below if other issues are discovered.

**Issues**
- [x] Newsletter block doesn't render. It uses jQuery and AJAX. This will need to be updated to support `<amp-form>` with `<action-xhr>`. The form will be updated to use AMP redirect after submission.
- [x] Notice block uses JS for dismissing the notice. This will need to be refactored later to work out a different method of hiding/showing notices since it currently defaults to hiding them and only shows them if the visitor has not dismissed it.
- [x] Pricing table block triggers an error due to `<span placeholder="$">`. Specifically the `placeholder` is the issue.
- [x] Sharing block uses JS and outputs it on every page on the `wp_footer` hook. Needs to be refactored to only output on regular non-AMP requests. Links on AMP requests will be normal links with no JS trigger.

### PR DESCRIPTION
**Pull request by mindctrl**
This PR address the AMP compatibility issues in the pricing, sharing, notice, and newsletter blocks.

**General testing**
Be sure to have pages with these blocks already configured before checking out this branch. This will be useful for testing for regressions and for testing the pricing table deprecation.

Run `npm run build-assets` after checking out this branch.

**Pricing**
The block was outputting a `<span placeholder="$">` element on the front end, which AMP flags as an issue. This PR deprecates the save routine and removes the placeholder from the span. To test this, be sure you have an existing pricing table page before running this branch. Then check out this branch, build the assets, and edit the pricing table page, and update the post. This should remove any AMP warnings related to the placeholder, and the pricing table should look and function the same as before.

**Sharing**
The share buttons normally trigger a modal via JS. Since we can't use the JS in AMP, we've turned the buttons into normal links that go direct to the social platform. Exception: the email button is not displayed on AMP requests. Why? Because AMP strips `mailto:` links. It appears the solution to this is their `amp-social-share` component, which requires a lot more work to match styling. For now we decided to not show the email button. We'll revisit this later and consider implementing the `amp-social-share` component.

**Notice**
For now the notice block output is not visible on AMP requests. Why? Because the notices default to `display: none` and are only made `display: block` when the JS checks localStorage and determines that the person has not dismissed it previously. Since `amp-script` is experimental and requires opting in for its use, we don't have much of a choice right now short of rewriting the way the block works. For AMP compatibility, we're just not loading the dismiss.js file this block uses for display/dismiss. This fixes the AMP warning but results in the notices not being shown. This is a short term compromise until we do a more thorough pass at this block.

**Newsletter**
The JS on this block causes AMP warnings. The JS is used for processing the submissions via Ajax requests. Since `amp-script` is experimental, we can't use it yet to create a similar/same experience on AMP requests. Since the JS doesn't load on AMP requests, we do page refresh/reloads after submission and show the success/failure messages on reload. We will revisit this at a later time after `amp-script` is stable.

Closes #111.

### CODE REVIEW

**Comment by nickcernis** [comment]
Nice work, @mindctrl!

Pricing, sharing, notices, and newsletter are all working for me. Some notes:

## Newsletter block
In AMP mode, the redirect after form submission fails for me if the site's not using HTTPS. I see this in the console:

```
error.js:198 AMP-Redirect-To Url must start with "https://" or "//" or be relative and served from either https or from localhost. Invalid value: http://dev.test/atomic-blocks-amp/?amp&ab-newsletter-submitted=1&ab-newsletter-submission-message=Thanks%20for%20subscribing.
```

This looks like a limitation of AMP ([redirect URLs must be HTTPS](https://amp.dev/documentation/components/amp-form#redirecting-after-a-submission)) rather than something we can correct, so probably not worth dealing with, especially since AMP itself requires HTTPS. (I tried skipping the schema to use `//` as the error suggests or using a relative URL, but it still complains about the lack of `https://`.)

It might be worth noting it in the changelog, though (“Newsletter block now works for AMP pages (requires HTTPS)”) in case it bites someone else during local testing.

## Notice block
Not showing it in AMP mode seems fine to me for now.

A next step might be to show the notice in AMP if “Notice Display” is set to “Always show” instead of “Dismissable” (because no JS/localStorage access should be needed in that case).

**Comment by dreamwhisper** [comment]
> A next step might be to show the notice in AMP if “Notice Display” is set to “Always show” instead of “Dismissable” (because no JS/localStorage access should be needed in that case).

Just noting in my test, the notice does display if I have it set to "Always Show".

**Comment by nickcernis** [comment]
> …the notice does display if I have it set to "Always Show".

I see the same now. Not sure why it didn't before.

**Comment by mikemcalister** [comment]
Killer work, @mindctrl! 

## Pricing

Deprecation worked great and validation error disappeared. Congrats on completing one of the most annoying tasks in WordPress! 

## Newsletter

I received the same error as @nickcernis about http/https, but the error is limited to local testing. Otherwise looks great. 

## Sharing 

Worked great. We can probably remove the Google+ sharing option in the next update to this block since they shut that service down recently. 

## Notice 

Looks good. Similar to @dreamwhisper and @nickcernis, this shows for me on the front end if Always Show is selected.

**Comment by mindctrl** [comment]
Thanks for the excellent reviews! I'm going to merge this and open a new issue for some of the suggestions on improving the sharing block.

**Pull request merged**
